### ISSUE TITLE
Add button for PIM

### ISSUE THREAD

**Issue by TargetCrafter** [Vertco/managemsp#2]
For companies working with Microsoft Privileged Identity Management it would be nice for users to have a direct link to the requests page so that they can ask for access to customers.

**Comment by harshleey** [comment]
Hello @TargetCrafter. Can I work on this?

**Comment by TargetCrafter** [comment]
@harshleey 
Sure thing, if you create a fork with the changes you can create a PR so we can merge this.

**Comment by TargetCrafter** [comment]
This is the request URL:
https://entra.microsoft.com/#view/Microsoft_Azure_PIMCommon/ActivationMenuBlade

**Comment by harshleey** [comment]
Alright

**Comment by harshleey** [comment]
Hello @TargetCrafter, do you want me to create it as part of the button URL as you did or as part of a hyperlink so you can access it once you click it?

**Comment by TargetCrafter** [comment]
I would just copy one of the existing buttons and create a second column. We might want to add some other buttons in the future.

**Comment by harshleey** [comment]
Created a pull request. Please check the code.
