### ISSUE TITLE
Drap and Drop animation stuck on when dragging away without dropping

### ISSUE THREAD

**Issue by Nathanymous** [Vertco/managemsp#25]
When dragging a file to the MSP manager, and dragging it away again without dropping the drop animation is stuck on.
This is fixed with a reload of the page or PWA.
![image](https://github.com/Vertco/MSP-Manager/assets/98420363/2c449172-64e9-4c84-b39f-145dea3dc9cd)

**Comment by TargetCrafter** [comment]
The drop file functionality has been removed in the latest release along with this bug.
